### ISSUE TITLE
Long search term causes redirect on 2015 port

### ISSUE THREAD

**Issue by michalhlavka** [planette/componette.com#115]
https://componette.com/search/?q=askldsadklnsaldasaskldsadklnsaldasaskldsadklnsaldasaskldsadklnsaldasaskldsadklnsaldasaskldsadklnsaldasaskldsadklnsaldasaskldsadklnsaldas

**Comment by adaamz** [comment]
Cannot reproduce on any browser Opera/Firefox/Chrome.

**Comment by michalhlavka** [comment]
The true fact is, that in anonymous windows it works correctly
